### ISSUE TITLE
After changing email in user settings you are no longer authenticated

### ISSUE THREAD

**Issue by ialmosara** [RahulSondhi/Tipsy#29]
After changing the email in user settings you are no longer authenticated for the account you originally logged into.

Steps to Reproduce:

1. Logged in user goes to user settings
2. User changes their email
3. User clicks on the Save Changes button
4. After leaving the settings page the user won't be able to perform any actions as the user they originally logged in as and only be redirected to a server error page.

What we should expect:
After changing the email the user should stay authenticated and still be able to interact with the app as that user.

TODO:
Edit the profile settings on the back end so the user stays authenticated

**Comment by bvalarezo** [comment]
This bug is irrelevant due to the new flow for User's changing email addresses. 

In order to change an email address, a user will must click on a verification link sent to their inbox of the new email address. Within the verifyNewEmail page, React will force the user to logout by deleting the stored access token(if available). The user must re login with their new email address in order to fetch an updated token from Spring.

Please see this commit for more details on the changes. 
[](https://github.com/RahulSondhi/Tipsy/commit/b191261ba73d7419940abe7958a5bd5600a9d848)
